import './state.test.js';
import './TodoClear.test.js';
import './TodoCount.test.js';
import './TodoDestroy.test.js';
import './TodoOnly.test.js';
import './TodoToggle.test.js';
import './TodoToggleAll.test.js';
import './TodoEdit.test.js';
import './TodoFilters.test.js';